controller_manager:
  ros__parameters:
    update_rate: 20  # Частота обновления в Гц

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    left_wheel_names: ["mount_1_to_wheel_1"]
    right_wheel_names: ["mount_2_to_wheel_2"]
    wheel_separation: 0.3
    wheel_radius: 0.05
    publish_rate: 20.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    cmd_vel_timeout: 0.5
    publish_odom: true
    publish_odom_tf: true
    odom_topic: /artist_robot/odom
    open_loop: false

joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - base_to_lift_arm
      - platform_to_brush_arm
      - arm_to_brush_tip
      - brush_tip_to_extension
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity